name: CI
env:
  FORCE_COLOR: 2
  NODE: 14
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE }}
      - name: Set up yarn cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/ms-playwright
            .yarn/cache
          key: ${{ runner.os }}-node-${{ env.NODE }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE }}-${{ hashFiles('yarn.lock') }}
      - run: yarn
      - run: yarn lint
      - run: yarn typecheck
  regression:
    name: Test regressions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE }}
      - name: Set up yarn cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/ms-playwright
            .yarn/cache
          key: ${{ runner.os }}-node-${{ env.NODE }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE }}-${{ hashFiles('yarn.lock') }}
      - run: yarn
      - run: yarn test-regression
  test:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 16
          - 14
          - 12
          - 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up yarn cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/ms-playwright
            .yarn/cache
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('yarn.lock') }}
      - run: yarn
      - run: yarn test
      - run: yarn test-browser
